# Python Imports
import json
import logging
import os
import pathlib
import shutil
import uuid
import threading as tr

# Library Imports
import psutil
from PySide6 import QtCore
from PySide6.QtCore import Qt
from PySide6.QtGui import QPixmap, QFont, QIcon
from PySide6.QtWidgets import QLabel, QMainWindow, QPushButton, QFileDialog, QMessageBox, QSpinBox, QListWidget, \
    QSlider, QCheckBox, QApplication, QComboBox

# Local Imports
from src.configs import PROJECT_DIR, HEADER_IMAGE, APP_ICON
from src.engine import AMAPEngine
from src.morph import AMAPMorphometry
from src.ui.ui_mainwindow import Ui_MainWindow
from src.ui.customization_dialog import CustomizationDialog
from src.utils import filter_tiff_files, analyze_tiff_files, create_progress_dialog, create_message_box, \
    open_dir_in_browser, cpu_threads_from_level, cpu_percent_from_level, batch_size_from_level, suggested_workers, \
    classify_project_inputs


class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()

        # This variable is used to prevent unnecessary writes while
        # configuring the projects
        self.is_loading = False
        # This variable is used to prevent signals causing problem
        # when UI elements are disabled
        self.is_disabled = True
        # Prevents double trigger of the timer
        self.is_triggered = False
        self.timer_time_out = 1000

        # Number of logical cores on this machine. Used to map the abstract
        # CPU/Mem allocation levels onto concrete values.
        self.cpu_count = psutil.cpu_count()
        # Upper bound for the data-loader workers slider. Capped at half the
        # logical cores: the worker processes compete with the PyTorch inference
        # threads for cores, so allowing the full count would oversubscribe the
        # CPU and inflate prefetch memory.
        self.max_workers = max(1, self.cpu_count // 2)

        # Will be instantiated when start button is clicked
        self.engine = None
        self.morphometry = None
        self.progress_dialog = None
        self.project_thread = None
        self.UI_state = None

        # These are ui elements that will be set in the configure_ui method
        self.app_icon = None
        self.button_add_project = None
        self.button_remove_project = None
        # This is a spin box to determine which channel is the tiff files are targeted
        self.spin_channel = None
        # This is a checkbox that determine whether the tiff images are stacked or not
        self.check_stacked = None
        # This is a checkbox that determine whether to use AMAP or AMAP-APP ROI detection
        self.check_old_roi = None
        # This is a checkbox that determine if we should include sd length analysis
        self.check_include_sd = None
        # This is a combobox to select the model checkpoint
        self.combo_checkpoint = None
        # This is a QListWidget that demonstrates projects list
        self.list_projects = None
        # This is a QSlider for resource allocation configuration
        self.slider_cpu = None
        # This is a QSlider for clustering precision configuration
        self.slider_mem = None
        # This is a QSlider for the number of data-loader workers. Its value is
        # derived from the CPU/Mem sliders but can be overridden by the user.
        self.slider_workers = None

        # We need to access these labels later
        self.label_cpu_alloc = None
        self.label_mem_alloc = None
        self.label_channel = None
        self.label_results = None
        self.label_workers = None
        # Smaller-font labels below each slider that show the computed value
        # (CPU percent/threads, batch size, worker count).
        self.label_cpu_value = None
        self.label_mem_value = None
        self.label_workers_value = None
        # Small-font status label describing the selected project's input images.
        self.label_input_info = None
        # Classification of the selected project's inputs (see
        # classify_project_inputs). Cached so the gating can be re-applied after
        # a run without re-reading the images.
        self._current_input_class = None
        self._current_n_channels = None

        # Start, Stop & Results buttons
        self.button_start = None
        self.button_stop = None
        self.button_results_segmentation = None
        self.button_results_morphometry = None

        # Ui_MainWindow class is autogenerated using "pyside6-uic" command
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.configure_ui()

    def configure_ui(self):

        self.setWindowTitle("AMAP")

        label = self.findChild(QLabel, "label_header")
        # The "Z003" font should be added to QFontDatabase before calling this method
        label.setFont(QFont("Z003", 36))

        label = self.findChild(QLabel, "label_image")
        label.setPixmap(QPixmap(HEADER_IMAGE))

        label = self.findChild(QLabel, "label_projects")
        label.setFont(QFont("Times", 14))

        label = self.findChild(QLabel, "label_cpu_allocation")
        label.setFont(QFont("Times", 14))

        label = self.findChild(QLabel, "label_mem_allocation")
        label.setFont(QFont("Times", 14))

        label = self.findChild(QLabel, "label_channel")
        label.setFont(QFont("Times", 14))

        label = self.findChild(QLabel, "label_checkpoint")
        label.setFont(QFont("Times", 14))

        label = self.findChild(QLabel, "label_results")
        label.setFont(QFont("Times", 14))

        # These are the labels that we need to access them later
        self.label_cpu_alloc = self.findChild(QLabel, "label_cpu_allocation")
        self.label_mem_alloc = self.findChild(QLabel, "label_mem_allocation")
        self.label_channel = self.findChild(QLabel, "label_channel")
        self.label_results = self.findChild(QLabel, "label_results")
        self.label_checkpoint = self.findChild(QLabel, "label_checkpoint")

        # Setting the window icon
        self.app_icon = QIcon(APP_ICON)
        self.setWindowIcon(self.app_icon)

        # Configuring Start, Stop & Results buttons
        self.button_start = self.findChild(QPushButton, "button_start")
        self.button_start.clicked.connect(self.start_project_click)

        self.button_stop = self.findChild(QPushButton, "button_stop")
        self.button_stop.clicked.connect(self.stop_project_click)

        self.button_results_segmentation = self.findChild(QPushButton, "button_result_segmentation")
        self.button_results_segmentation.clicked.connect(self.segmentation_result_click)

        self.button_results_morphometry = self.findChild(QPushButton, "button_result_morphometry")
        self.button_results_morphometry.clicked.connect(self.morphometry_result_click)

        self.button_reset = self.findChild(QPushButton, "button_reset")
        self.button_reset.clicked.connect(self.reset_project_results)

        # Handling Add Project button's click
        self.button_add_project = self.findChild(QPushButton, "button_add_project")
        self.button_add_project.clicked.connect(self.add_project_click)

        # Handling Remove Project button's click
        self.button_remove_project = self.findChild(QPushButton, "button_remove_project")
        self.button_remove_project.clicked.connect(self.remove_project)

        # Handling spin box changes
        self.spin_channel = self.findChild(QSpinBox, "spin_channel")
        self.spin_channel.valueChanged.connect(self.spin_channel_change)

        # Handling resource slider changes
        self.slider_cpu = self.findChild(QSlider, "slider_cpu_allocation")
        self.slider_cpu.valueChanged.connect(self.slider_cpu_allocation_change)

        # Handling precision slider changes
        self.slider_mem = self.findChild(QSlider, "slider_mem_allocation")
        self.slider_mem.valueChanged.connect(self.slider_mem_allocation_change)

        # Handling data-loader workers slider changes. The slider is an absolute
        # count, capped at half the logical cores (see self.max_workers).
        self.slider_workers = self.findChild(QSlider, "slider_workers")
        self.slider_workers.setMaximum(self.max_workers)
        self.slider_workers.valueChanged.connect(self.slider_workers_change)
        self.label_workers = self.findChild(QLabel, "label_workers")
        self.label_workers.setFont(QFont("Times", 14))

        # The smaller-font value labels sit beneath each slider and display the
        # concrete value the slider maps to. They are updated by the _refresh_*
        # helpers, not edited by the user.
        value_font = QFont("Times", 10)
        value_font.setItalic(True)
        self.label_cpu_value = self.findChild(QLabel, "label_cpu_value")
        self.label_cpu_value.setFont(value_font)
        self.label_mem_value = self.findChild(QLabel, "label_mem_value")
        self.label_mem_value.setFont(value_font)
        self.label_workers_value = self.findChild(QLabel, "label_workers_value")
        self.label_workers_value.setFont(value_font)

        # Status label describing the selected project's input images.
        self.label_input_info = self.findChild(QLabel, "label_input_info")
        self.label_input_info.setFont(value_font)

        # Handling stacked checkbox changes
        self.check_stacked = self.findChild(QCheckBox, "check_stacked")
        self.check_stacked.stateChanged.connect(self.checkbox_stack_change)
        self.check_old_roi = self.findChild(QCheckBox, "check_old_roi")
        self.check_old_roi.stateChanged.connect(self.checkbox_old_roi_change)
        self.check_include_sd = self.findChild(QCheckBox, "check_include_sd")
        self.check_include_sd.toggled.connect(self.checkbox_include_sd_change)
        self.check_use_gpu = self.findChild(QCheckBox, "check_use_gpu")
        self.check_use_gpu.stateChanged.connect(self.checkbox_use_gpu_change)
        self.button_customize = self.findChild(QPushButton, "button_customize")
        self.button_customize.clicked.connect(self.open_customization_dialog)

        # Handling checkpoint combo box
        self.combo_checkpoint = self.findChild(QComboBox, "combo_checkpoint")
        self.populate_checkpoint_combo()
        self.combo_checkpoint.currentTextChanged.connect(self.checkpoint_change)

        # Handling list of projects
        self.list_projects = self.findChild(QListWidget, "list_widget_projects")
        self.list_projects.setFont(QFont("Times", 18))
        self.list_projects.itemClicked.connect(self.activate_selected_project)

        self.load_projects()

    # Load project configurations and enables the UI buttons
    def activate_selected_project(self, _selected_item):
        self.is_loading = True

        project_name = _selected_item.text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)

        # Inspect the project's images to decide which input options apply, and
        # persist the classification (older projects predate it; read_file and
        # the gating below rely on it).
        input_class, n_channels, input_description = classify_project_inputs(
            project_configs['source_dir'])
        self._current_input_class = input_class
        self._current_n_channels = n_channels
        config_dirty = False
        if project_configs.get('input_class') != input_class or \
                project_configs.get('n_channels') != n_channels:
            project_configs['input_class'] = input_class
            project_configs['n_channels'] = n_channels
            config_dirty = True
        # A 4D input is always a stack, so make that explicit in the config.
        if input_class == 'homogeneous_4d' and not project_configs.get('is_stacked'):
            project_configs['is_stacked'] = True
            config_dirty = True
        if config_dirty:
            self.save_project_configuration(project_configs_path, project_configs)
        self.label_input_info.setText(input_description)
        self.label_input_info.setEnabled(True)

        self.slider_cpu.setValue(project_configs['cpu_allocation'])
        self.slider_cpu.setEnabled(True)
        self.label_cpu_alloc.setEnabled(True)

        self.slider_mem.setValue(project_configs['mem_allocation'])
        self.slider_mem.setEnabled(True)
        self.label_mem_alloc.setEnabled(True)

        # Legacy projects predate the workers slider: derive a sensible default
        # from their CPU/Mem levels, bounded by this machine's worker cap.
        workers = project_configs.get(
            'num_workers',
            suggested_workers(project_configs['cpu_allocation'],
                              project_configs['mem_allocation'],
                              self.max_workers))
        self.slider_workers.setValue(workers)
        self.slider_workers.setEnabled(True)
        self.label_workers.setEnabled(True)

        # Reflect the freshly loaded slider values in the value labels.
        self._refresh_cpu_label()
        self._refresh_mem_label()
        self._refresh_workers_label()
        self._sync_value_label_states()

        self.spin_channel.setValue(project_configs['target_channel'])
        self.spin_channel.setEnabled(True)

        self.check_old_roi.setChecked(project_configs['is_old_roi'])
        self.check_old_roi.setEnabled(True)

        self.check_include_sd.setChecked(project_configs.get('does_include_sd', False))
        self.check_include_sd.setEnabled(True)

        self.check_use_gpu.setChecked(project_configs.get('use_gpu', True))
        self.check_use_gpu.setEnabled(True)

        self.button_customize.setEnabled(True)

        checkpoint = project_configs.get('model_checkpoint', 'original.pth')
        idx = self.combo_checkpoint.findText(checkpoint)
        if idx >= 0:
            self.combo_checkpoint.setCurrentIndex(idx)
        self.combo_checkpoint.setEnabled(True)
        self.label_checkpoint.setEnabled(True)

        self.check_stacked.setChecked(project_configs['is_stacked'])
        self.check_stacked.setEnabled(True)
        self.label_channel.setEnabled(True)

        self.label_results.setEnabled(True)
        self.button_results_segmentation.setEnabled(project_configs['is_segmentation_finished'])
        self.button_results_morphometry.setEnabled(project_configs['is_morphometry_finished'])
        # Reset is available whenever there are results to clear (lets the project be re-run).
        self.button_reset.setEnabled(project_configs['is_segmentation_finished']
                                     or project_configs['is_morphometry_finished'])

        self.button_start.setEnabled(not project_configs['is_morphometry_finished'])
        self.check_stacked.setEnabled(not project_configs['is_morphometry_finished'])
        self.check_old_roi.setEnabled(not project_configs['is_morphometry_finished'])
        self.check_include_sd.setEnabled(not project_configs['is_morphometry_finished'])
        self.check_use_gpu.setEnabled(not project_configs['is_morphometry_finished'])
        self.button_customize.setEnabled(not project_configs['is_morphometry_finished'])
        self.spin_channel.setEnabled(not project_configs['is_morphometry_finished'])
        self.combo_checkpoint.setEnabled(not project_configs['is_morphometry_finished'])
        self.slider_workers.setEnabled(not project_configs['is_morphometry_finished'])
        self.button_stop.setEnabled(False)

        # Gate the Stacked / Target-channel controls to the detected input class.
        # This is the final word on their enabled state, so it must run after the
        # blanket enabling above.
        self._apply_input_gating(input_class, n_channels,
                                 project_configs['is_morphometry_finished'])

        self.button_remove_project.setEnabled(True)

        self.is_disabled = False
        self.is_loading = False

    # Enable the Stacked / Target-channel controls only for the input classes
    # they apply to, and bound the channel spin box to the real channel count.
    # See classify_project_inputs (utils) and read_file (dataset).
    def _apply_input_gating(self, _input_class, _n_channels, _finished):
        if _input_class == 'homogeneous_3d':
            stacked_enabled, channel_enabled = True, True
        elif _input_class == 'homogeneous_4d':
            # A 4D input is always a stack: force the checkbox on and lock it.
            self.check_stacked.setChecked(True)
            stacked_enabled, channel_enabled = False, True
        else:  # homogeneous_2d or heterogeneous: neither control applies
            stacked_enabled, channel_enabled = False, False

        self.check_stacked.setEnabled(stacked_enabled and not _finished)

        if channel_enabled and _n_channels:
            self.spin_channel.setMaximum(max(0, _n_channels - 1))
        else:
            self.spin_channel.setMaximum(20)
        self.spin_channel.setEnabled(channel_enabled and not _finished)
        self.label_channel.setEnabled(channel_enabled and not _finished)

    # Changes the channel configuration for the selected project
    def spin_channel_change(self, _value):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['target_channel'] = _value
        self.save_project_configuration(project_configs_path, project_configs)

    # Changes the stacked configuration for the selected project
    def checkbox_stack_change(self, _value):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['is_stacked'] = True if _value == 2 else False
        self.save_project_configuration(project_configs_path, project_configs)

    # Changes the stacked configuration for the selected project
    def checkbox_old_roi_change(self, _value):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['is_old_roi'] = True if _value == 2 else False
        self.save_project_configuration(project_configs_path, project_configs)

    # Changes the GPU usage configuration for the selected project
    def checkbox_use_gpu_change(self, _value):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['use_gpu'] = True if _value == 2 else False
        self.save_project_configuration(project_configs_path, project_configs)

    # Opens the customization dialog to edit ROI/post-processing hyperparameters
    def open_customization_dialog(self):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        dialog = CustomizationDialog(project_configs,
                                     project_configs.get('is_old_roi', False),
                                     self)
        if dialog.exec():
            project_configs.update(dialog.values())
            self.save_project_configuration(project_configs_path, project_configs)

    # Deletes all results so the project can be re-run (asks for confirmation first)
    def reset_project_results(self):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        questionBox = QMessageBox()
        questionBox.setWindowIcon(self.app_icon)
        questionBox.setFont(QFont("Times", 14))
        questionBox.setIcon(QMessageBox.Warning)
        answer = questionBox.question(
            self, '',
            f'All results for "{project_name}" (segmentation, morphometry and intermediate '
            f'files) will be deleted so the project can be re-run.\n\nAre you sure?',
            questionBox.Yes | questionBox.No)
        if answer != questionBox.Yes:
            return

        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        for key in ('result_segmentation_dir', 'npy_dir', 'result_morphometry_dir'):
            directory = project_configs.get(key)
            if directory and os.path.isdir(directory):
                for entry in os.listdir(directory):
                    path = os.path.join(directory, entry)
                    try:
                        if os.path.isdir(path):
                            shutil.rmtree(path)
                        else:
                            os.remove(path)
                    except OSError:
                        logging.exception("Could not remove %s", path)

        project_configs['is_segmentation_finished'] = False
        project_configs['is_morphometry_finished'] = False
        self.save_project_configuration(project_configs_path, project_configs)
        # Refresh the UI for this project so it becomes runnable again.
        self.activate_selected_project(self.list_projects.currentItem())

    # Populates the checkpoint combo box with available model files
    def populate_checkpoint_combo(self):
        self.combo_checkpoint.clear()
        checkpoint_dir = "res/model/"
        if os.path.exists(checkpoint_dir):
            checkpoint_files = [f for f in os.listdir(checkpoint_dir) if f.endswith('.pth')]
            self.combo_checkpoint.addItems(checkpoint_files)
        if self.combo_checkpoint.count() == 0:
            self.combo_checkpoint.addItem("original.pth")

    # Changes the checkpoint configuration for the selected project
    def checkpoint_change(self, _text):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['model_checkpoint'] = _text
        self.save_project_configuration(project_configs_path, project_configs)

    # Changes the stacked configuration for the selected project
    def checkbox_include_sd_change(self, _value):
        if self.is_disabled or self.is_loading:
            return

        # Only show confirmation dialog when checking the checkbox (False to True)
        if _value == True:  # Qt.Checked = 2
            # Show confirmation dialog
            questionBox = QMessageBox()
            questionBox.setWindowIcon(self.app_icon)
            questionBox.setFont(QFont("Times", 14))
            questionBox.setIcon(QMessageBox.Warning)
            questionBox.setText('The SD length analysis feature may potentially conflict with patents filed subsequent to the AMAP paper publication.\n\n'
                              'The authors of AMAP-APP do not hold ownership of any such patent.\n'
                              'Users are solely responsible for ensuring compliance with all applicable intellectual property regulations and legal requirements.\n'
                              'The authors disclaim any responsibility for misuse of this feature or any resulting legal consequences.\n\n'
                              'Do you acknowledge the above notice and wish to include SD length analysis in your results?')
            questionBox.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            questionBox.setDefaultButton(QMessageBox.No)
            answer = questionBox.exec()

            if answer == questionBox.No:
                # User declined, revert the checkbox to unchecked state
                self.check_include_sd.setChecked(False)
                return

        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['does_include_sd'] = self.check_include_sd.isChecked()
        self.save_project_configuration(project_configs_path, project_configs)

    # Changes the resource configuration for the selected project
    def slider_cpu_allocation_change(self, _value):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['cpu_allocation'] = _value
        self.save_project_configuration(project_configs_path, project_configs)
        self._refresh_cpu_label()
        # One-way link: re-derive the workers suggestion from the (now saved)
        # CPU level and the current Mem level, and push it onto the workers slider.
        self._apply_suggested_workers(_value, self.slider_mem.value())

    # Changes the precision configuration for the selected project
    def slider_mem_allocation_change(self, _value):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['mem_allocation'] = _value
        self.save_project_configuration(project_configs_path, project_configs)
        self._refresh_mem_label()
        # One-way link: re-derive the workers suggestion from the current CPU
        # level and the (now saved) Mem level.
        self._apply_suggested_workers(self.slider_cpu.value(), _value)

    # Changes the data-loader workers configuration for the selected project.
    # This is the user-facing override of the CPU/Mem-derived suggestion and
    # deliberately does NOT touch the CPU/Mem sliders (one-way link).
    def slider_workers_change(self, _value):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)
        project_configs['num_workers'] = _value
        self.save_project_configuration(project_configs_path, project_configs)
        self._refresh_workers_label()

    # Pushes the CPU/Mem-derived worker suggestion onto the workers slider.
    # setValue fires slider_workers_change (which persists num_workers); the
    # explicit label refresh covers the case where the value is unchanged and
    # the signal does not fire.
    def _apply_suggested_workers(self, _cpu_level, _mem_level):
        self.slider_workers.setValue(suggested_workers(_cpu_level, _mem_level, self.max_workers))
        self._refresh_workers_label()

    # The small value labels below each slider show the concrete value the
    # slider maps to. They read straight from the sliders so they are safe to
    # call during load. The title labels above stay as fixed captions.
    def _refresh_cpu_label(self):
        level = self.slider_cpu.value()
        self.label_cpu_value.setText(
            "%d%% · %d threads" % (
                cpu_percent_from_level(level),
                cpu_threads_from_level(level, self.cpu_count)))

    def _refresh_mem_label(self):
        self.label_mem_value.setText(
            "batch size %d" % batch_size_from_level(self.slider_mem.value()))

    def _refresh_workers_label(self):
        self.label_workers_value.setText("%d workers" % self.slider_workers.value())

    # Keep each value label greyed/enabled in step with its slider.
    def _sync_value_label_states(self):
        self.label_cpu_value.setEnabled(self.slider_cpu.isEnabled())
        self.label_mem_value.setEnabled(self.slider_mem.isEnabled())
        self.label_workers_value.setEnabled(self.slider_workers.isEnabled())

    def stop_project_click(self):
        self.button_stop.setEnabled(False)
        self.engine.cancel()
        self.progress_dialog.setLabelText('Cancelling... it will take some time.')
        self.engine = None

    def start_project_click(self):
        self.UI_state = self.save_UI_state()
        self.list_projects.setEnabled(False)
        self.disable_UI()
        self.button_add_project.setEnabled(False)
        self.button_stop.setEnabled(True)

        self.progress_dialog = create_progress_dialog('Segmentation', 'Please wait', self)

        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)

        if not project_configs['is_segmentation_finished']:
            self.engine = AMAPEngine(project_configs)
            self.project_thread = tr.Thread(target=self.start_project_segmentation)
            self.project_thread.start()

        QtCore.QTimer.singleShot(500, self.check_project_status)

        self.progress_dialog.show()

    def check_project_status(self):
        if self.is_triggered:
            return
        else:
            self.is_triggered = True
        proceed = True
        try:
            if self.project_thread is not None and self.project_thread.is_alive():
                if self.engine is not None:
                    percentage = self.engine.processed_tiles.value / len(self.engine.dataset) * 100
                    # Something in Qt prevent us to set the percentage to 100
                    if percentage > 99:
                        percentage = 99
                    self.progress_dialog.setValue(percentage)
                elif self.morphometry is not None:
                    percentage = (self.morphometry.no_of_processed_images[0]) / self.morphometry.no_of_images[0] * 100
                    if percentage > 99:
                        percentage = 99
                    self.progress_dialog.setValue(percentage)

            else:
                project_name = self.list_projects.currentItem().text()
                project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
                project_configs = self.load_project_configuration(project_configs_path)

                if project_configs['is_segmentation_finished'] and not project_configs['is_morphometry_finished']:
                    # Segmentation Finished
                    if self.morphometry is None:
                        self.button_stop.setEnabled(False)
                        self.morphometry = AMAPMorphometry(project_configs)
                        self.project_thread = tr.Thread(target=self.start_project_morphometry)
                        self.progress_dialog.setLabelText('Morphometry')
                        self.project_thread.start()

                else:
                    # Cancelled or finished
                    proceed = False

                    self.progress_dialog.close()
                    self.restore_UI_state(self.UI_state)
                    self.is_disabled = False
                    self.button_stop.setEnabled(False)

                    project_configs = self.load_project_configuration(project_configs_path)
                    if project_configs['is_segmentation_finished'] and project_configs['is_morphometry_finished']:
                        self.button_results_morphometry.setEnabled(True)
                        self.button_results_segmentation.setEnabled(True)
                        self.button_start.setEnabled(False)
                        self.check_old_roi.setEnabled(False)
                        self.check_include_sd.setEnabled(False)
                        self.check_stacked.setEnabled(False)
                        self.check_use_gpu.setEnabled(False)
                        self.spin_channel.setEnabled(False)
                        self.slider_workers.setEnabled(False)
                        self._sync_value_label_states()
                    else:
                        self.button_start.setEnabled(True)

                    # Reset is available once results exist; customization follows the run state.
                    self.button_reset.setEnabled(project_configs['is_segmentation_finished']
                                                 or project_configs['is_morphometry_finished'])
                    self.button_customize.setEnabled(not project_configs['is_morphometry_finished'])

                    self.UI_state = None
                    self.project_thread = None
                    self.progress_dialog = None
                    self.engine = None
                    self.morphometry = None

        finally:
            self.is_triggered = False
            if proceed:
                QtCore.QTimer.singleShot(self.timer_time_out, self.check_project_status)

    def start_project_morphometry(self):
        if self.morphometry:
            self.morphometry.exec()

    def start_project_segmentation(self):
        if self.engine:
            self.engine.exec()

    def segmentation_result_click(self):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)

        open_dir_in_browser(project_configs['result_segmentation_dir'])

    def morphometry_result_click(self):
        if self.is_disabled or self.is_loading:
            return
        project_name = self.list_projects.currentItem().text()
        project_configs_path = f'./{PROJECT_DIR}/{project_name}/conf.json'
        project_configs = self.load_project_configuration(project_configs_path)

        open_dir_in_browser(project_configs['result_morphometry_dir'])

    def add_project_click(self):
        selected_directory = str(QFileDialog.getExistingDirectory(self, "Select Directory"))
        if selected_directory == '':
            return

        selected_path = pathlib.PurePath(selected_directory)
        app_path = pathlib.PurePath(os.getcwd())

        # Checking for the cases that user can select a wrong path
        # The case that the project directory itself is selected
        if selected_path.parent.name == app_path.name:
            msgBox = create_message_box("You should not select projects directory. That's naughty!\n"
                                        "Please select another directory.",
                                        self.app_icon)
            msgBox.exec()
            return

        # The case that one of the directories inside project is selected
        if selected_path.parent.parent.name == app_path.name:
            msgBox = create_message_box("This project is already imported.\n"
                                        "Please select another directory.",
                                        self.app_icon)
            msgBox.exec()
            return

        # The case that no tif/tiff file exists in the selected directory
        tiff_files = filter_tiff_files(selected_directory)
        if len(tiff_files) == 0:
            msgBox = create_message_box("The selected directory doesn't contain any tif/tiff images.\n"
                                        "Currently, AMAP only support tif/tiff format.\n"
                                        "Please select another directory.",
                                        self.app_icon)
            msgBox.exec()
            return

        # The case that project already exits
        if os.path.exists(f"{os.getcwd()}/{PROJECT_DIR}/{selected_path.name}"):
            msgBox = create_message_box("The project already exists.\n"
                                        "Please remove the old one or rename the new one.",
                                        self.app_icon)
            msgBox.exec()
            return

        # Copying the selected directory and images to the project
        destination_directory = f"{os.getcwd()}/{PROJECT_DIR}/{selected_path.name}/"

        progressDialog = create_progress_dialog(f'Creating project "{selected_path.name}"', 'Please wait', self)
        progressDialog.show()
        QApplication.processEvents()

        # Checking the dimensionality of the images.
        # It should be the same for all images that belong to a project
        is_valid, is_stacked, dimensions = analyze_tiff_files(selected_directory)

        if not is_valid:
            progressDialog.close()
            logging.error('The shape of the last image is different from the rest.\n' + dimensions)
            msgBox = create_message_box("The dimension of all images in a project should be the same. "
                                        "The app will create a max projection of the images.",
                                        self.app_icon)
            msgBox.exec()

        os.mkdir(destination_directory)

        images_directory = os.path.join(destination_directory, 'images/')
        os.mkdir(images_directory)

        for tiff_image in tiff_files:
            # Prevents UI freeze
            QApplication.processEvents()

            full_name = os.path.join(selected_directory, tiff_image)
            if os.path.isfile(full_name):
                shutil.copy(full_name, images_directory)

        # Classify the inputs so read_file and the UI know how to handle them.
        input_class, n_channels, _ = classify_project_inputs(images_directory)
        # A 4D input is always a stack.
        if input_class == 'homogeneous_4d':
            is_stacked = True

        # Saving the configuration file into the project directory (Do not confuse with 'Projects' dir)
        project_configuration = {
            "project_id": f"{uuid.uuid4()}",
            "project_name": f"{selected_path.name}",
            "base_dir": f"./{PROJECT_DIR}/{selected_path.name}/",
            "source_dir": f"./{PROJECT_DIR}/{selected_path.name}/images/",
            "npy_dir": f"./{PROJECT_DIR}/{selected_path.name}/npy/",
            "result_segmentation_dir": f"./{PROJECT_DIR}/{selected_path.name}/segmentation/",
            "result_morphometry_dir": f"./{PROJECT_DIR}/{selected_path.name}/morphometry/",
            "cpu_allocation": 4,
            "mem_allocation": 2,
            "target_channel": 0,
            "batch_size": 8,
            "dimensionality": 16,
            "is_stacked": is_stacked,
            "input_class": input_class,
            "n_channels": n_channels,
            "is_segmentation_finished": False,
            "is_morphometry_finished": False,
            "is_old_roi": False,
            "does_include_sd": False,
            "use_gpu": True,
            "model_checkpoint": "original.pth",
            "num_workers": suggested_workers(4, 2, self.max_workers)
        }
        self.save_project_configuration(f"{destination_directory}/conf.json", project_configuration)
        self.load_projects()

        progressDialog.close()

        logging.info(f'Project "{selected_path.name}" created.')

    def remove_project(self):
        project_name = self.list_projects.currentItem().text()
        questionBox = QMessageBox()
        questionBox.setWindowIcon(self.app_icon)
        questionBox.setFont(QFont("Times", 14))
        answer = questionBox.question(self,
                                      '',
                                      f'The project "{project_name}" will be removed."\nAre you sure?',
                                      questionBox.Yes | questionBox.No)
        if answer == questionBox.Yes:
            def delete_project_dir(_project_name):
                project_path = f"./{PROJECT_DIR}/{_project_name}/"
                if os.path.exists(project_path):
                    shutil.rmtree(project_path)

            delete_project_dir(project_name)
            self.load_projects()
            self.list_projects.clearSelection()
            self.disable_UI()

            logging.info(f'Project "{project_name}" removed.')

    def disable_UI(self):
        self.slider_cpu.setEnabled(False)
        self.label_cpu_alloc.setEnabled(False)
        self.slider_mem.setEnabled(False)
        self.label_mem_alloc.setEnabled(False)
        self.slider_workers.setEnabled(False)
        self.label_workers.setEnabled(False)
        self.spin_channel.setEnabled(False)
        self.check_stacked.setEnabled(False)
        self.check_old_roi.setEnabled(False)
        self.check_include_sd.setEnabled(False)
        self.check_use_gpu.setEnabled(False)
        self.label_channel.setEnabled(False)
        self.combo_checkpoint.setEnabled(False)
        self.label_checkpoint.setEnabled(False)
        self.button_start.setEnabled(False)
        self.button_stop.setEnabled(False)
        self.button_remove_project.setEnabled(False)
        self.button_reset.setEnabled(False)
        self.button_customize.setEnabled(False)
        self.label_results.setEnabled(False)
        self.button_results_segmentation.setEnabled(False)
        self.button_results_morphometry.setEnabled(False)
        # Grey out the input status line (its text is kept so it survives a run).
        self.label_input_info.setEnabled(False)
        self.is_disabled = True

        self.slider_cpu.setValue(0)
        self.slider_mem.setValue(0)
        self.slider_workers.setValue(0)
        # Clear the value labels so a deselected project shows no stale numbers.
        self.label_cpu_value.clear()
        self.label_mem_value.clear()
        self.label_workers_value.clear()
        self._sync_value_label_states()

    def save_UI_state(self):
        return (self.slider_cpu.isEnabled(),
                self.label_cpu_alloc.isEnabled(),
                self.slider_mem.isEnabled(),
                self.label_mem_alloc.isEnabled(),
                self.spin_channel.isEnabled(),
                self.check_stacked.isEnabled(),
                self.label_channel.isEnabled(),
                self.button_results_segmentation.isEnabled(),
                self.button_start.isEnabled(),
                self.button_stop.isEnabled(),
                self.button_add_project.isEnabled(),
                self.button_remove_project.isEnabled(),
                self.slider_cpu.value(),
                self.slider_mem.value(),
                self.spin_channel.value(),
                self.list_projects.isEnabled(),
                self.label_results.isEnabled(),
                self.button_results_segmentation.isEnabled(),
                self.button_results_morphometry.isEnabled(),
                self.check_old_roi.isEnabled(),
                self.check_include_sd.isEnabled(),
                self.combo_checkpoint.isEnabled(),
                self.label_checkpoint.isEnabled(),
                self.check_use_gpu.isEnabled(),
                self.slider_workers.isEnabled(),
                self.slider_workers.value(),
                self.label_workers.isEnabled(),
                )

    def restore_UI_state(self, _UI_state):
        self.is_loading = True
        self.slider_cpu.setEnabled(_UI_state[0])
        self.label_cpu_alloc.setEnabled(_UI_state[1])
        self.slider_mem.setEnabled(_UI_state[2])
        self.label_mem_alloc.setEnabled(_UI_state[3])
        self.spin_channel.setEnabled(_UI_state[4])
        self.check_stacked.setEnabled(_UI_state[5])
        self.check_old_roi.setEnabled(_UI_state[19])
        self.check_include_sd.setEnabled(_UI_state[20])
        self.label_channel.setEnabled(_UI_state[6])
        self.button_results_segmentation.setEnabled(_UI_state[7])
        self.button_start.setEnabled(_UI_state[8])
        self.button_stop.setEnabled(_UI_state[9])
        self.button_add_project.setEnabled(_UI_state[10])
        self.button_remove_project.setEnabled(_UI_state[11])
        self.slider_cpu.setValue(_UI_state[12])
        self.slider_mem.setValue(_UI_state[13])
        self.spin_channel.setValue(_UI_state[14])
        self.list_projects.setEnabled(_UI_state[15])
        self.label_results.setEnabled(_UI_state[16]),
        self.button_results_segmentation.setEnabled(_UI_state[17]),
        self.button_results_morphometry.setEnabled(_UI_state[18]),
        self.combo_checkpoint.setEnabled(_UI_state[21])
        self.label_checkpoint.setEnabled(_UI_state[22])
        self.check_use_gpu.setEnabled(_UI_state[23])
        self.slider_workers.setEnabled(_UI_state[24])
        self.slider_workers.setValue(_UI_state[25])
        self.label_workers.setEnabled(_UI_state[26])
        self._sync_value_label_states()
        # Re-apply input gating (Stacked / Target channel) for the active project
        # and bring back the input status line.
        self._apply_input_gating(self._current_input_class, self._current_n_channels, False)
        self.label_input_info.setEnabled(True)
        self.is_loading = False

    def load_projects(self):
        project_dirs = [directory.name for directory in os.scandir(f"./{PROJECT_DIR}/") if directory.is_dir()]
        for directory in project_dirs:
            temp_item = self.list_projects.findItems(directory, Qt.MatchExactly)
            if len(temp_item) == 0:
                self.list_projects.addItem(directory)

        items = [self.list_projects.item(x) for x in range(self.list_projects.count())]
        for item in items:
            item_text = item.text()
            if item_text not in project_dirs:
                # Removing widgets from QListWidget is not working as intended
                # at the moment, so this is the way to go
                listItems = self.list_projects.selectedItems()
                if not listItems:
                    return
                self.list_projects.takeItem(self.list_projects.row(item))

    @staticmethod
    def save_project_configuration(_path, _configs):
        with open(_path, 'w+') as file:
            file.write(json.dumps(_configs))

    @staticmethod
    def load_project_configuration(_path):
        with open(_path, 'r') as file:
            return json.load(file)
